alias gs="git status"
alias gb="git branch --sort=-committerdate"
alias gc="git checkout"
alias gl="git log --oneline --decorate --color"
alias gd="git diff"
alias gp="git push"
alias gpl="git pull"
alias ga="git add"
alias gcmsg="git commit -m"
alias gca="git commit --amend --no-edit"
alias gstash="git stash -u"
alias gpop="git stash pop"
alias gclean="git clean -df && git reset --hard"
alias gprune="git fetch --prune"
alias gforce="git push --force-with-lease"
alias gwip="git add . && git commit -m wip"
alias gunstage="git restore --staged ."
alias gresolve="git add . && git commit --no-edit"