#!/usr/bin/env bash
#
# LiteLLM proxy + Phoenix observability — Dockerized
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"
LOCAL_DIR="$DOTFILES_DIR/.local"
LITELLM_ENV_SOURCE="$LOCAL_DIR/litellm.env.local"

# ---------- Prerequisites ----------
if ! command -v docker &>/dev/null; then
  echo "  [FAIL] Docker is not installed. Install Docker Desktop or Rancher Desktop first."
  exit 1
fi

if ! docker info &>/dev/null; then
  echo "  [FAIL] Docker daemon is not running. Start Docker first."
  exit 1
fi

# ---------- Source secrets from the single source of truth ----------
if [ ! -f "$LOCAL_DIR/.env.local" ]; then
  echo "  [FAIL] $LOCAL_DIR/.env.local not found. Run script/bootstrap first."
  exit 1
fi

set -a
source "$LOCAL_DIR/.env.local"
set +a

if [ -z "${PERSONAL_OPENCODE_API_KEY:-}" ] || [ "$PERSONAL_OPENCODE_API_KEY" = "sk-" ]; then
  echo "  [FAIL] PERSONAL_OPENCODE_API_KEY is not set in $LOCAL_DIR/.env.local"
  exit 1
fi

if [ -z "${PERSONAL_DEEPSEEK_API_KEY:-}" ] || [ "$PERSONAL_DEEPSEEK_API_KEY" = "sk-" ]; then
  echo "  [FAIL] PERSONAL_DEEPSEEK_API_KEY is not set in $LOCAL_DIR/.env.local"
  exit 1
fi

# ---------- LITELLM_KEY: generate once, persist in .local/.env.local ----------
if [ -z "${LITELLM_KEY:-}" ]; then
  # 128 bits of randomness (openssl rand, present on macOS base system).
  LITELLM_KEY="sk-litellm-local-dev-$(openssl rand -hex 16)"
  printf '\n# LiteLLM proxy admin key (auto-generated by litellm/install.sh)\nLITELLM_KEY=%s\n' "$LITELLM_KEY" >> "$LOCAL_DIR/.env.local"
  echo "  [ ..] Generated LITELLM_KEY=$LITELLM_KEY (saved to $LOCAL_DIR/.env.local)"
else
  echo "  [ OK] Using existing LITELLM_KEY from $LOCAL_DIR/.env.local"
fi

# ---------- Generate env file in .local/ only ----------
# Secrets NEVER live in the repo scope. docker compose reads it via
# --env-file at command time; no litellm/.env is created or left behind.
mkdir -p "$LOCAL_DIR"
{
  echo "# Auto-generated by litellm/install.sh — do not edit manually"
  echo "# Source of truth: .local/.env.local"
  echo "LITELLM_KEY=$LITELLM_KEY"
  echo "PERSONAL_OPENCODE_API_KEY=$PERSONAL_OPENCODE_API_KEY"
  echo "PERSONAL_DEEPSEEK_API_KEY=$PERSONAL_DEEPSEEK_API_KEY"
} > "$LITELLM_ENV_SOURCE"
chmod 600 "$LITELLM_ENV_SOURCE"

# Remove any stale secret file/symlink previously left in the litellm/ scope.
rm -f "$DOTFILES_DIR/litellm/.env"

# ---------- Kill old launchd services ----------
for PLIST in ai.phoenix ai.litellm; do
  if launchctl list "$PLIST" &>/dev/null 2>&1; then
    echo "  [ ..] Unloading old launchd service: $PLIST"
    launchctl unload "$HOME/Library/LaunchAgents/$PLIST.plist" 2>/dev/null || true
    rm -f "$HOME/Library/LaunchAgents/$PLIST.plist"
  fi
done

# ---------- Kill stale processes on our ports ----------
# Skip Rancher/lima VM port-forward processes (their SSH tunnels hold these
# ports); killing them takes down the whole Docker engine. Compose-managed
# containers release their own ports on recreate.
for PORT in 4000 4317 6006; do
  for PID in $(lsof -ti :"$PORT" 2>/dev/null || true); do
    CMD=$(ps -p "$PID" -o command= 2>/dev/null || true)
    case "$CMD" in
      *rancher-desktop*|*lima*|*ssh.sock*) continue ;;
    esac
    echo "  [ ..] Killing stale process on port $PORT (PID $PID)"
    kill "$PID" 2>/dev/null || true
    sleep 1
  done
done

# ---------- Docker Compose ----------
cd "$DOTFILES_DIR/litellm"

# Secrets come from .local/litellm.env.local via --env-file; the litellm/
# directory never holds a secret file.
COMPOSE=(docker compose --env-file "$LITELLM_ENV_SOURCE")

echo "  [ ..] Building Docker images..."
"${COMPOSE[@]}" build --pull 2>&1 | tail -3

echo "  [ ..] Starting stack..."
"${COMPOSE[@]}" up -d 2>&1 | tail -5

# ---------- Verify ----------
echo ""
echo "  Waiting for services to become healthy..."

for i in $(seq 1 12); do
  if curl -sf http://localhost:4000/health -H "Authorization: Bearer $LITELLM_KEY" \
    | python3 -c "import sys,json;d=json.load(sys.stdin);exit(0 if d.get('healthy_count',0)>0 else 1)" 2>/dev/null; then
    echo "  [ OK] LiteLLM is healthy (http://localhost:4000)"
    break
  fi
  if [ "$i" -eq 12 ]; then
    echo "  [WARN] LiteLLM not ready after 60s — check 'docker compose logs litellm'"
  fi
  sleep 5
done

for i in $(seq 1 12); do
  if curl -sf http://localhost:6006 -o /dev/null 2>&1; then
    echo "  [ OK] Phoenix UI is up (http://localhost:6006)"
    break
  fi
  if [ "$i" -eq 12 ]; then
    echo "  [WARN] Phoenix not ready after 60s — check 'docker compose logs phoenix'"
  fi
  sleep 5
done

# ---------- Seed Phoenix (pricing + evaluators) ----------
echo ""
echo "  [ ..] Seeding Phoenix pricing (generative_models + token_prices)..."
docker exec -i postgres psql -U phoenix -d phoenix < "$DOTFILES_DIR/litellm/db/pricing.sql" 2>&1 | grep -v "^$" || true
echo "  [ OK] Pricing seeded."

echo "  [ ..] Ensuring DeepSeek evaluator custom provider exists..."
if ! docker exec postgres psql -U phoenix -d phoenix -tAc \
    "SELECT 1 FROM generative_model_custom_providers WHERE name='deepseek-official-eval'" 2>/dev/null | grep -q 1; then
  # The provider's API key is encrypted server-side, so it must be created via
  # Phoenix's GraphQL API (never via SQL, never in the repo).
  if [ -n "${PERSONAL_DEEPSEEK_API_KEY:-}" ]; then
    python3 - "$PERSONAL_DEEPSEEK_API_KEY" <<'PYEOF'
import json, sys, urllib.request
key = sys.argv[1]
body = json.dumps({
  "query": "mutation($i: CreateGenerativeModelCustomProviderMutationInput!){createGenerativeModelCustomProvider(input:$i){provider{id name}}}",
  "variables": {"i": {
    "name": "deepseek-official-eval",
    "description": "DeepSeek official API for evaluator judge calls",
    "provider": "openai",
    "clientConfig": {"openai": {
      "openaiAuthenticationMethod": {"apiKey": key},
      "openaiClientKwargs": {"baseUrl": "https://api.deepseek.com/v1"},
    }},
  }},
}).encode()
req = urllib.request.Request("http://localhost:6006/graphql", data=body,
                             headers={"Content-Type": "application/json"})
resp = json.loads(urllib.request.urlopen(req, timeout=60).read().decode())
if "errors" in resp:
    sys.stderr.write(json.dumps(resp["errors"]))
    sys.exit(1)
print("  [ OK] Created custom provider deepseek-official-eval")
PYEOF
  else
    echo "  [WARN] PERSONAL_DEEPSEEK_API_KEY not set — skipping custom provider creation."
  fi
else
  echo "  [ OK] Custom provider deepseek-official-eval already exists."
fi

echo "  [ ..] Seeding Phoenix evaluators (task_accuracy LLM judge)..."
docker exec -i postgres psql -U phoenix -d phoenix < "$DOTFILES_DIR/litellm/db/evaluators.sql" 2>&1 | grep -v "^$" || true
echo "  [ OK] Evaluators seeded."

echo "  [ OK] LLM stack is running."
echo ""
echo "  Manual compose commands (must pass --env-file for secrets):"
echo "    docker compose --env-file .local/litellm.env.local -f litellm/docker-compose.yml up -d"
echo "    docker compose --env-file .local/litellm.env.local -f litellm/docker-compose.yml down"
echo "    docker compose --env-file .local/litellm.env.local -f litellm/docker-compose.yml logs -f litellm"
echo "    (or just re-run litellm/install.sh)"
echo ""
echo "  URLs:"
echo "    http://localhost:4000            LiteLLM proxy"
echo "    http://localhost:6006            Phoenix UI"
echo "    https://litellm.localhost         LiteLLM (via Caddy)"
echo "    https://phoenix.localhost         Phoenix (via Caddy)"
