#!/usr/bin/env bash
#
# Generate k8s .env in .local/ and deploy via kustomize
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"
LOCAL_DIR="$DOTFILES_DIR/.local"
K8S_DIR="$DOTFILES_DIR/k8s"
K8S_ENV_SOURCE="$LOCAL_DIR/k8s.env.local"
K8S_ENV_TEMP="$K8S_DIR/.env"

if [ ! -f "$LOCAL_DIR/.env.local" ]; then
  echo "  [FAIL] $LOCAL_DIR/.env.local not found. Run script/bootstrap first."
  exit 1
fi

set -a
source "$LOCAL_DIR/.env.local"
set +a

mkdir -p "$LOCAL_DIR"
{
  echo "# Auto-generated by k8s/setup.sh — do not edit manually"
  echo "# Source of truth: .local/.env.local"
  echo "LITELLM_KEY=${LITELLM_KEY:-}"
  echo "PERSONAL_OPENCODE_API_KEY=$PERSONAL_OPENCODE_API_KEY"
  echo "PERSONAL_DEEPSEEK_API_KEY=${PERSONAL_DEEPSEEK_API_KEY:-}"
  echo "PHOENIX_DB_PASSWORD=${PHOENIX_DB_PASSWORD:-phoenix}"
} > "$K8S_ENV_SOURCE"
chmod 600 "$K8S_ENV_SOURCE"

# kustomize's secretGenerator reads .env from the kustomization dir, so create a
# TEMPORARY .env here, deploy, then delete it immediately. Secrets never persist
# outside .local/.
cp "$K8S_ENV_SOURCE" "$K8S_ENV_TEMP"

if command -v kubectl &>/dev/null && kubectl cluster-info &>/dev/null 2>&1; then
  echo "  [ ..] Deploying with kustomize..."
  kubectl apply -k "$K8S_DIR"
else
  echo "  [ ..] kubectl not available / cluster unreachable — skipping apply."
  echo "         Re-run k8s/setup.sh when ready to deploy."
fi

rm -f "$K8S_ENV_TEMP"
echo "  [ OK] Generated $K8S_ENV_SOURCE (secrets stay in .local/)"
echo "       Temp $K8S_ENV_TEMP created during apply and removed."
